bump colorama to 0.1.17 due to debugger error
============================== 1 passed in 0.06s ===============================
Exception ignored in atexit callback: <function reset_all at 0x7ff51526b910>
Traceback (most recent call last):
  File "/home/shane/nutra/cli/.venv/lib/python3.10/site-packages/colorama/initialise.py", line 13, in reset_all
    AnsiToWin32(orig_stdout).reset_all()
  File "/home/shane/nutra/cli/.venv/lib/python3.10/site-packages/colorama/ansitowin32.py", line 127, in reset_all
    self.wrapped.write(Style.RESET_ALL)
ValueError: I/O operation on closed file.