that's crap man, 3.3 argparse is busted
Run n -v
  n -v
  nutra -d recipe init
  nutra --no-pager recipe
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.3.7/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.3.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.3.7/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.3.7/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.3.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.3.7/x64/lib
nutra cli version 0.2.6.dev3 [DB usda v0.0.8, nt v0.0.6]
Console size: 24h x 80w
WARN: ~/.nutra/prefs.json doesn't exist, using defaults
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.3.7/x64/bin/nutra", line 12, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.3.7/x64/lib/python3.3/site-packages/ntclient/__main__.py", line 121, in main
WARN: ~/.nutra/prefs.json doesn't contain valid PROFILE_ID,proceeding in bare mode
Unforeseen error, run with -d for more info: TypeError("recipes() got an unexpected keyword argument 'args'",)
    exit_code, *_results = func(_parser)
Executed in: 4.0 ms
Exit code: 1
  File "/opt/hostedtoolcache/Python/3.3.7/x64/lib/python3.3/site-packages/ntclient/__main__.py", line 105, in func
    return parser.func(args=parser)  # type: ignore
TypeError: recipes() got an unexpected keyword argument 'args'